version: '2'

services:
  app-db:
    build: database
    container_name: database-container
    restart: always

  frontend:
    build: client
    ports:
      - "8080:8080"
    container_name: frontend-container
    restart: always

  backend:
    build: .
    ports:
      - "5000:5000"
    container_name: backend-container
    restart: always
    depends_on:
      - app-db
    links:
      - app-db
